// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateServiceInput struct {
	Name string `json:"name"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type ServiceType struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Services    []*Service `json:"services"`
}

type Technician struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}
