version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  api:
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: ./graphql-api/Dockerfile.dev
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - .:/app
    command:
      - gin
      - run
      - main.go
